name: PO-UI DEVELOPMENT DEPLOY

# URL para os pacotes po-ui no npm
env:
  SCHEMATICS_NPM_PATH: teste-poui-deploy/ng-schematics
  WORKING_DIR: /home/runner/work/po-angular-testes-spike/po-angular-testes-spike/po-angular

on:
    push:
        branches:
            - development

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

    - name: Check out po-angular
      uses: actions/checkout@v4
      with:
        path: po-angular

    - name: Check out style
      uses: actions/checkout@v4
      with:
        repository: po-ui/po-style
        path: po-style

    - name: Check out lint
      uses: actions/checkout@v4
      with:
        repository: po-ui/po-tslint
        path: po-tslint

    - name: Install and Build
      run: npm install && npm run build
      working-directory: ${{env.WORKING_DIR}}

    # Pega a versão no package.json
    - name: Get package.json version.
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
      with:
        path: po-angular

    # PUBLISH NG-SCHEMATICS
    - name: ng-schematics - publish
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish ${{env.WORKING_DIR}}/dist/ng-schematics --tag beta --ignore-scripts
      env:
        PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Trigger Azure DevOps Pipeline THF-COMPONENTS
      uses: Azure/pipelines@v1.2
      with:
        azure-devops-project-url: 'https://dev.azure.com/totvstfs/THF'
        azure-pipeline-name: 'thf-components-development-ci'
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'